import Link from "next/link";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/access";
import { requestReadScope } from "@/lib/rbac";

export default async function RequestsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const user = await requireUser(); const params = await searchParams;
  const scope = requestReadScope(user);
  const rows = await db.request.findMany({ where: { ...scope, ...(params.status ? { status: params.status as never } : {}), ...(params.q ? { OR: [{ requestNumber: { contains: params.q, mode: "insensitive" } }, { payee: { displayName: { contains: params.q, mode: "insensitive" } } }, { lines: { some: { particulars: { contains: params.q, mode: "insensitive" } } } }] } : {}) }, include: { company: true, payee: true, requester: true }, orderBy: { updatedAt: "desc" }, take: 100 });
  return <><div className="form-head"><div><span className="eyebrow">Request register</span><h1>My Requests</h1></div><Link className="button" href="/requests/new">+ New request</Link></div><form className="card actions"><input name="q" defaultValue={params.q} placeholder="Request, payee or particulars"/><select name="status" defaultValue={params.status}><option value="">All statuses</option><option>DRAFT</option><option>PENDING_MANAGER_APPROVAL</option><option>RETURNED_FOR_REVISION</option><option>PENDING_AP_VALIDATION</option><option>PAID</option><option>CLOSED</option></select><button className="button">Search</button></form><section className="section table-wrap"><table><thead><tr><th>Reference</th><th>Requester / Payee</th><th>Company</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/requests/${row.id}`}><strong>{row.requestNumber ?? row.draftIdentifier}</strong></Link><div className="fine">v{row.currentVersion}</div></td><td>{row.requester.fullName}<div className="fine">{row.payee.displayName}</div></td><td>{row.company.code}</td><td>{row.requestDate.toLocaleDateString()}</td><td>{row.currency} {row.totalAmount.toFixed(2)}</td><td><span className="badge">{row.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></section></>;
}
