import { notFound } from "next/navigation";
import { canReadRequest, requireUser } from "@/lib/access";
import { db } from "@/lib/db";
import Link from "next/link";
import { adjustAccountingLineAction, confirmManualPostingAction, copyRequestAction, decisionAction, generatePdfAction, quickBooksAction, reconcileAction, recordPaymentAction, transitionAction, uploadDocumentAction } from "@/app/actions";
import { hasPermission } from "@/lib/rbac";

export default async function RequestDetails({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser(); const { id } = await params;
  const row = await db.request.findUnique({ where: { id }, include: { company: { include: { branding: true } }, requester: true, payee: true, natureOfPayment: true, lines: { include: { projectCode: true, account: true, adjustedProjectCode: true, adjustedAccount: true }, orderBy: { position: "asc" } }, assignments: true, decisions: { include: { approver: true }, orderBy: { createdAt: "desc" } }, attestations: { include: { user: true } }, documents: true, generatedDocuments: { orderBy: { version: "desc" } }, qbExports: { orderBy: { version: "desc" } }, payments: true, reconciliation: true, histories: { orderBy: { createdAt: "desc" } }, comments: { include: { author: true }, orderBy: { createdAt: "desc" } } } });
  if (!row) notFound(); if (!canReadRequest(user, row)) return <div className="notice">Record-level access denied.</div>;
  const [availableProjects,availableAccounts]=await Promise.all([db.projectCode.findMany({where:{companyId:row.companyId,active:true},orderBy:{code:"asc"}}),db.account.findMany({where:{companyId:row.companyId,active:true},orderBy:{name:"asc"}})]);
  const assigned = row.assignments.some((a) => a.approverId === user.id && !a.completedAt && !a.invalidatedAt);
  const editable=row.requesterId===user.id&&["DRAFT","RETURNED_FOR_REVISION","RETURNED_BY_AP"].includes(row.status);
  const canUpload = hasPermission(user, "document.upload");
  return <><div className="form-head"><div><span className="eyebrow">{row.company.name}</span><h1>{row.requestNumber ?? row.draftIdentifier}</h1><div className="actions"><span className="badge">{row.status.replaceAll("_", " ")}</span><span className="fine">Version {row.currentVersion} · updated {row.updatedAt.toLocaleString()}</span></div></div><div className="actions">{editable&&<Link className="button" href={`/requests/${row.id}/edit`}>Edit / resubmit</Link>}{(row.requesterId===user.id||user.roles.includes("ADMIN"))&&<form action={copyRequestAction}><input type="hidden" name="requestId" value={row.id}/><button className="button secondary">Copy request</button></form>}{["AP_PROCESSOR","ADMIN"].some((r) => user.roles.includes(r)) && <form action={generatePdfAction}><input type="hidden" name="requestId" value={row.id}/><button className="button secondary">Generate versioned PDF</button></form>}{["AP_PROCESSOR","AP_REVIEWER"].some((r) => user.roles.includes(r)) && <form action={quickBooksAction}><input type="hidden" name="requestId" value={row.id}/><button className="button">Generate QB CSV</button></form>}</div></div>
      <div className="grid grid-2"><section className="card"><h2>REQUEST FOR PAYMENT FORM</h2><dl><dt className="label">COMPANY NAME</dt><dd>{row.company.name}</dd><dt className="label">DATE</dt><dd>{row.requestDate.toLocaleDateString()}</dd><dt className="label">REQUESTOR</dt><dd>{row.requester.fullName}</dd><dt className="label">PAYEE</dt><dd>{row.payee.displayName}</dd><dt className="label">CURRENCY</dt><dd>{row.currency}</dd><dt className="label">NATURE OF PAYMENT</dt><dd>{row.natureOfPayment.displayLabel}{row.paymentOtherText ? ` — ${row.paymentOtherText}` : ""}</dd></dl></section><section className="card"><h2>Controlled references</h2><dl><dt className="label">Internal invoice</dt><dd>{row.invoiceNumber ?? "Pending"}</dd><dt className="label">APV</dt><dd>{row.apvNumber ?? "Pending"}</dd><dt className="label">Generated PDFs</dt><dd>{row.generatedDocuments.length ? row.generatedDocuments.map((d) => <a className="button secondary" key={d.id} href={`/api/generated/${d.id}`}>Download v{d.version} · {d.sha256.slice(0, 12)}…</a>) : "None"}</dd><dt className="label">QuickBooks output</dt><dd>{row.qbExports.length ? `${row.qbExports.length} version(s)` : "Not generated"}</dd><dt className="label">Attachments</dt><dd>{row.documents.length}</dd></dl></section></div>
    <section className="section card"><h2>Accounting lines</h2><div className="table-wrap"><table><thead><tr><th>#</th><th>Project Code</th><th>Account</th><th>Particulars</th><th>Amount</th></tr></thead><tbody>{row.lines.map((line, i) => <tr key={line.id}><td>{i + 1}</td><td>{line.adjustedProjectCode?.code ?? line.projectCode?.code ?? line.projectCodeText}</td><td>{line.adjustedAccount?.name ?? line.account?.name ?? line.accountText ?? <span className="badge red">Mapping required</span>}</td><td>{line.particulars}</td><td>{row.currency} {line.amount.toFixed(2)}</td></tr>)}</tbody><tfoot><tr><th colSpan={4}>TOTAL AMOUNT</th><th>{row.currency} {row.totalAmount.toFixed(2)}</th></tr></tfoot></table></div></section>
    {["AP_PROCESSOR","AP_REVIEWER","ADMIN"].some(r=>user.roles.includes(r))&&<section className="section card"><h2>AP accounting adjustments</h2><p className="muted">Requester originals remain immutable; adjustments and reasons are separately audited.</p>{row.lines.map((line,i)=><form key={line.id} action={adjustAccountingLineAction} className="line-grid"><input type="hidden" name="requestId" value={row.id}/><input type="hidden" name="lineId" value={line.id}/><div className="field"><label>Line {i+1} project</label><select name="projectCodeId" defaultValue={line.adjustedProjectCodeId??line.projectCodeId??""}>{availableProjects.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></div><div className="field"><label>Adjusted account</label><select name="accountId" defaultValue={line.adjustedAccountId??line.accountId??""}><option value="">Select</option>{availableAccounts.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="field"><label>Reason</label><input name="reason" required/></div><button className="button">Save adjustment</button></form>)}</section>}
    <section className="section card"><div className="form-head"><div><h2>Supporting Documents</h2><p className="muted">Authorized download is served through controlled handlers; raw storage keys are never public.</p></div></div><div className="actions">{row.documents.map(d=><a key={d.id} className="button secondary" href={`/api/documents/${d.id}`}>{d.category}: {d.originalFilename}</a>)}</div>{canUpload && <form action={uploadDocumentAction} className="actions section"><input type="hidden" name="requestId" value={row.id}/><select name="category"><option>INVOICE</option><option>OFFICIAL_RECEIPT</option><option>BILLING_STATEMENT</option><option>PAYROLL_BREAKDOWN</option><option>CONTRACT</option><option>PROOF_OF_PAYMENT</option><option>EXPENSE_BREAKDOWN</option><option>OTHER</option></select><input name="file" type="file" required/><button className="button">Upload securely</button></form>}</section>
    {assigned && <section className="section card"><h2>Approval decision</h2><form action={decisionAction} className="grid"><input type="hidden" name="requestId" value={row.id}/><div className="field"><label>COMMENT (required for return/rejection)</label><textarea name="comment"/></div><label><input name="attested" value="true" type="checkbox"/> I have reviewed this request and its supporting documents and approve it for further accounting processing.</label><div className="actions"><button className="button" name="decision" value="APPROVED">Approve</button><button className="button secondary" name="decision" value="RETURNED">Return for revision</button><button className="button danger" name="decision" value="REJECTED">Reject</button></div></form></section>}
    {["AP_PROCESSOR","AP_REVIEWER","ADMIN"].some((r) => user.roles.includes(r)) && <section className="section card"><h2>Workflow controls</h2><form action={transitionAction} className="actions"><input type="hidden" name="requestId" value={row.id}/><select name="to"><option>PENDING_AP_VALIDATION</option><option>READY_FOR_DOCUMENT_GENERATION</option><option>DOCUMENT_GENERATED</option><option>REPOSITORY_SAVE_PENDING</option><option>READY_FOR_QUICKBOOKS</option><option>QUICKBOOKS_FILE_GENERATED</option><option>QUICKBOOKS_POSTING_PENDING</option><option>POSTED_TO_QUICKBOOKS</option><option>PAYMENT_SCHEDULED</option><option>PAYMENT_PROCESSING</option><option>PAID</option><option>RECONCILIATION_PENDING</option><option>RECONCILED</option><option>CLOSED</option><option>ON_HOLD</option></select><input name="comment" placeholder="Reason / control evidence"/><button className="button">Apply validated transition</button></form></section>}
    {["AP_PROCESSOR","AP_REVIEWER","ADMIN"].some(r=>user.roles.includes(r))&&<section className="section card"><h2>Confirm manual QuickBooks posting</h2><form action={confirmManualPostingAction} className="grid grid-2"><input type="hidden" name="requestId" value={row.id}/><div className="field"><label>QuickBooks transaction ID</label><input name="transactionId" required/></div><div className="field"><label>APV number</label><input name="apvNumber" required/></div><div className="field"><label>Posting date</label><input type="date" name="postingDate" required/></div><div className="field"><label>Evidence reference</label><input name="evidenceReference" required/></div><button className="button">Confirm posting with evidence</button></form></section>}
    {["AP_PROCESSOR","ADMIN"].some((r)=>user.roles.includes(r)) && <div className="grid grid-2 section"><section className="card"><h2>Record payment</h2><form action={recordPaymentAction} className="grid"><input type="hidden" name="requestId" value={row.id}/><div className="field"><label>Amount</label><input name="amount" inputMode="decimal" required/></div><div className="field"><label>Method</label><select name="method"><option>BANK_TRANSFER</option><option>CHECK</option><option>GCASH</option></select></div><div className="field"><label>Payment reference</label><input name="reference" required/></div><button className="button">Record confirmed payment</button></form></section><section className="card"><h2>Reconcile</h2><form action={reconcileAction} className="grid"><input type="hidden" name="requestId" value={row.id}/><div className="field"><label>Bank reference</label><input name="bankReference" required/></div><div className="field"><label>Settlement date</label><input type="date" name="settlementDate" required/></div><div className="field"><label>Settled amount</label><input name="settledAmount" inputMode="decimal" required/></div><div className="field"><label>Variance reason</label><input name="varianceReason"/></div><button className="button">Record reconciliation</button></form></section></div>}
    <div className="grid grid-2 section"><section className="card"><h2>Signatures and decisions</h2>{row.attestations.map((a) => <p key={a.id}><strong>REQUESTOR&apos;S SIGNATURE</strong><br/>{a.user.fullName} · {a.createdAt.toLocaleString()} · v{a.requestVersion}</p>)}{row.decisions.map((d) => <p key={d.id}><strong>APPROVER&apos;S SIGNATURE / DECISION</strong><br/>{d.approver.fullName} · {d.decision} · {d.createdAt.toLocaleString()}<br/><span className="muted">{d.comment}</span></p>)}</section><section className="card"><h2>Request timeline</h2><ol className="timeline">{row.histories.map((h) => <li key={h.id}><strong>{h.toStatus.replaceAll("_", " ")}</strong><div className="fine">{h.createdAt.toLocaleString()} · version {h.requestVersion}</div>{h.reason && <div>{h.reason}</div>}</li>)}</ol></section></div></>;
}
