"use client";

import { useFieldArray, useForm, useWatch } from "react-hook-form";
import Decimal from "decimal.js";
import { createRequestAction, updateDraftAction } from "@/app/actions";

type Option = { id: string; name: string; code?: string };
type FormValues = { companyId: string; requestDate: string; payeeId: string; currency: string; natureOfPaymentCode: string; paymentOtherText: string; conditionalData: Record<string, string>; lines: { projectCodeId: string; accountId: string; particulars: string; amount: string }[]; attested: boolean };

const conditional: Record<string, { key: string; label: string }[]> = {
  GCASH: [{ key: "recipientName", label: "Recipient name" }, { key: "mobileNumber", label: "GCash mobile number (masked in lists)" }],
  CASH_ADVANCE: [{ key: "custodian", label: "Employee / custodian" }, { key: "businessPurpose", label: "Business purpose" }, { key: "liquidationDate", label: "Expected liquidation date" }],
  CREDIT_CARD: [{ key: "cardReference", label: "Cardholder / masked reference" }],
  GOVERNMENT_REMITTANCE: [{ key: "agency", label: "Agency" }, { key: "period", label: "Period" }, { key: "dueDate", label: "Due date" }, { key: "remittanceType", label: "Remittance type" }],
  BANK_TRANSFER: [{ key: "approvedBankDetailsRef", label: "Approved payee bank-detail reference" }],
  DOLLAR_PURCHASE: [{ key: "foreignCurrencyDetails", label: "Foreign-currency details" }],
  DEBIT_MEMO: [{ key: "relatedTransaction", label: "Related transaction" }]
};

export function RequestForm({ companies, payees, projectCodes, accounts, paymentTypes, requesterName, requestId, initial }: { companies: Option[]; payees: Option[]; projectCodes: Option[]; accounts: Option[]; paymentTypes: { code: string; displayLabel: string }[]; requesterName: string; requestId?: string; initial?: Partial<FormValues> }) {
  const defaults: FormValues = { companyId: companies[0]?.id ?? "", requestDate: new Date().toISOString().slice(0, 10), payeeId: "", currency: "PHP", natureOfPaymentCode: "", paymentOtherText: "", conditionalData: {}, lines: [{ projectCodeId: "", accountId: "", particulars: "", amount: "" }], attested: false, ...initial };
  const { register, control, handleSubmit, setValue, formState: { errors, isSubmitting } } = useForm<FormValues>({ defaultValues: defaults });
  const { fields, append, remove, move } = useFieldArray({ control, name: "lines" });
  const lines = useWatch({ control, name: "lines" }); const payment = useWatch({ control, name: "natureOfPaymentCode" });
  const total = lines.reduce((sum, line) => { try { return sum.plus(line.amount || 0); } catch { return sum; } }, new Decimal(0)).toFixed(2);
  const submit = (intent: "draft" | "submit") => handleSubmit(async (value) => { const data = new FormData(); data.set("payload", JSON.stringify({ ...value, conditionalData: value.conditionalData ?? {} })); data.set("intent", intent); data.set("attested", String(value.attested)); if (requestId) { data.set("requestId", requestId); await updateDraftAction(data); } else await createRequestAction(data); })();

  return <div><div className="form-section"><div className="company-head"><div className="svi-logo">SVI</div><div><strong>SVI Technologies Inc.</strong><div className="fine">22/F Antel Global Corporate Center · Pasig City, Philippines</div></div></div><h1 className="form-title">REQUEST FOR PAYMENT FORM</h1><div className="grid grid-2"><div className="field"><label>COMPANY NAME</label><select {...register("companyId", { required: true })}>{companies.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>DATE</label><input type="date" {...register("requestDate", { required: true })}/></div><div className="field"><label>REQUESTOR</label><input value={requesterName} readOnly aria-readonly="true"/></div><div className="field"><label>PAYEE</label><select {...register("payeeId", { required: "Payee is required" })}><option value="">Select payee</option>{payees.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>{errors.payeeId && <span className="error">{errors.payeeId.message}</span>}</div><div className="field"><label>CURRENCY</label><select {...register("currency", { required: true })}><option>PHP</option><option>USD</option></select></div></div></div>
    <div className="form-section"><div className="form-head"><div><h2>Request line items</h2><p className="muted">Project Code · Account · Particulars · Amount</p></div><button type="button" className="button secondary" onClick={() => append({ projectCodeId: "", accountId: "", particulars: "", amount: "" })}>+ Add line</button></div>{fields.map((field, index) => <div className="line-grid" key={field.id}><div className="field"><label>PROJECT CODE</label><select {...register(`lines.${index}.projectCodeId`, { required: true })}><option value="">Select</option>{projectCodes.map((x) => <option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="field"><label>ACCOUNT</label><select {...register(`lines.${index}.accountId`)}><option value="">Accounting to complete</option>{accounts.map((x) => <option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="field"><label>PARTICULARS</label><textarea {...register(`lines.${index}.particulars`, { required: true, minLength: 10, maxLength: 1000 })}/></div><div className="field"><label>AMOUNT</label><input inputMode="decimal" placeholder="0.00" {...register(`lines.${index}.amount`, { required: true, pattern: /^\d+(\.\d{1,4})?$/, validate: (x) => Number(x) > 0 })}/></div><div className="actions"><button type="button" className="button secondary" aria-label={`Duplicate line ${index + 1}`} onClick={() => append({ ...lines[index] })}>⧉</button>{index > 0 && <button type="button" className="button secondary" aria-label={`Move line ${index + 1} up`} onClick={() => move(index, index - 1)}>↑</button>}<button type="button" className="button secondary" aria-label={`Remove line ${index + 1}`} disabled={fields.length === 1} onClick={() => remove(index)}>×</button></div></div>)}<div className="total"><span>TOTAL AMOUNT</span><span>{total}</span></div></div>
    <div className="form-section"><h2>NATURE OF PAYMENT</h2><div className="grid grid-4">{paymentTypes.map((type) => <label key={type.code}><input type="radio" value={type.code} {...register("natureOfPaymentCode", { required: true })}/> {type.displayLabel}</label>)}</div>{payment === "OTHERS" && <div className="field section"><label>Please specify</label><input {...register("paymentOtherText", { required: payment === "OTHERS" })}/></div>}{(conditional[payment] ?? []).length > 0 && <div className="grid grid-2 section">{conditional[payment].map((item) => <div className="field" key={item.key}><label>{item.label}</label><input {...register(`conditionalData.${item.key}`, { required: true })}/></div>)}</div>}</div>
    <div className="form-section"><h2>REQUESTOR&apos;S SIGNATURE</h2><label><input type="checkbox" {...register("attested")}/> I certify that the information in this request is complete and accurate and that the supporting documents are authentic and relevant to the payment being requested.</label><p className="fine">Your authenticated identity, timestamp, request version and session fingerprint are recorded.</p></div>
    <div className="actions"><button className="button secondary" disabled={isSubmitting} onClick={() => submit("draft")}>Save draft</button><button className="button" disabled={isSubmitting} onClick={() => { setValue("attested", true, { shouldValidate: true }); void submit("submit"); }}>{requestId ? "Attest and resubmit" : "Attest and submit"}</button></div></div>;
}
